batch_size: 8
charset:
- a
- b
- c
- d
- e
- f
- g
- h
- i
- j
- k
- l
- m
- n
- o
- p
- q
- r
- s
- t
- u
- v
- w
- x
- y
- z
- A
- B
- C
- D
- E
- F
- G
- H
- I
- J
- K
- L
- M
- N
- O
- P
- Q
- R
- S
- T
- U
- V
- W
- X
- Y
- Z
- '0'
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- "\u0905"
- "\u0906"
- "\u0907"
- "\u0908"
- "\u0909"
- "\u090A"
- "\u090F"
- "\u0910"
- "\u0913"
- "\u0914"
- "\u0915"
- "\u0916"
- "\u0917"
- "\u0918"
- "\u091A"
- "\u091B"
- "\u091C"
- "\u091D"
- "\u091F"
- "\u0920"
- "\u0921"
- "\u0922"
- "\u0924"
- "\u0925"
- "\u0926"
- "\u0927"
- "\u0928"
- "\u092A"
- "\u092B"
- "\u092C"
- "\u092D"
- "\u092E"
- "\u092F"
- "\u0930"
- "\u0932"
- "\u0935"
- "\u0936"
- "\u0937"
- "\u0938"
- "\u0939"
- "\u0C05"
- "\u0C06"
- "\u0C07"
- "\u0C08"
- "\u0C09"
- "\u0C0A"
- "\u0C0E"
- "\u0C0F"
- "\u0C10"
- "\u0C12"
- "\u0C13"
- "\u0C15"
- "\u0C16"
- "\u0C17"
- "\u0C18"
- "\u0C1A"
- "\u0C1B"
- "\u0C1C"
- "\u0C1D"
- "\u0C1F"
- "\u0C20"
- "\u0C21"
- "\u0C22"
- "\u0C24"
- "\u0C25"
- "\u0C26"
- "\u0C27"
- "\u0C28"
- "\u0C2A"
- "\u0C2B"
- "\u0C2C"
- "\u0C2D"
- "\u0C2E"
- "\u0C2F"
- "\u0C30"
- "\u0C32"
- "\u0C35"
- "\u0C36"
- "\u0C37"
- "\u0C38"
- "\u0C39"
- "\u0C85"
- "\u0C86"
- "\u0C87"
- "\u0C88"
- "\u0C89"
- "\u0C8A"
- "\u0C8E"
- "\u0C8F"
- "\u0C90"
- "\u0C92"
- "\u0C93"
- "\u0C95"
- "\u0C96"
- "\u0C97"
- "\u0C98"
- "\u0C9A"
- "\u0C9B"
- "\u0C9C"
- "\u0C9D"
- "\u0C9F"
- "\u0CA0"
- "\u0CA1"
- "\u0CA2"
- "\u0CA4"
- "\u0CA5"
- "\u0CA6"
- "\u0CA7"
- "\u0CA8"
- "\u0CAA"
- "\u0CAB"
- "\u0CAC"
- "\u0CAD"
- "\u0CAE"
- "\u0CAF"
- "\u0CB0"
- "\u0CB2"
- "\u0CB5"
- "\u0CB6"
- "\u0CB7"
- "\u0CB8"
- "\u0CB9"
lr: 0.0003
